{{- if .Values.rollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end}}
metadata:
  name: "{{ .Values.application.name }}-app"
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: "{{ .Values.application.name }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Values.application.name }}-app"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: "{{ .Values.application.name }}-app"
          ports:
            - containerPort: {{ .Values.image.containerPort | default 8080 }}
          env:
            - name: SEMVER
              value: "{{.Values.image.tag}}"
            - name: STAGE
              value: {{.Values.kargo.stage}}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{ if .Values.services.s3.enabled }}
            - name: S3_BUCKET_NAME
              value: "{{ .Values.services.s3.bucketName }}"
            {{ end }}
  minReadySeconds: 30
  revisionHistoryLimit: 3
  {{- if .Values.rollouts.enabled }}
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      canaryService: svc-canary  # required
      stableService: svc-stable # required
      trafficRouting:
        nginx:
          stableIngress: stable-ingress
      analysis:
        templates:
        - templateName: success-rate
        startingStep: 4
      maxSurge: '25%'
      maxUnavailable: 0
      steps:
        - setWeight: 10
        - pause:
            duration: 20s 
        - setWeight: 20
        - analysis:
            templates:
            - templateName: loadgen
        - pause:
            duration: 20s 
        - setWeight: 50
        - pause:
            duration: 1m 
        - setWeight: 75
        - pause:
            duration: 20s 
        - setWeight: 100
  {{- end  }}