apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: kyverno-policy-check
spec:
  command:
    - /ko-app/kubectl-kyverno
    - version
  image: ghcr.io/kyverno/kyverno-cli:66a2ff7afd893222113f938252dfbcf1b5eb2397
  output:
    source:
      format: Text
      type: Stdout
    transform:
      version: 'trim(output) == "" ? [] : split(trim(output), "\n")'
