apiVersion: ee.kargo.akuity.io/v1alpha1
kind: CustomPromotionStep
metadata:
  name: opa-test
spec:
  command:
    - sh
    - -c
    - >-
      conftest test \
        --no-color \
        --output=table \
        --update=https://raw.githubusercontent.com/jessesuen/kargo-custom-steps/master/policy/kubernetes.rego \
        --policy=/tmp/policy \
        ${{ config.path }} \
        > /tmp/output
  image: openpolicyagent/conftest:v0.67.0
  output:
    source:
      format: Text
      path: /tmp/output
      type: File
    transform:
      output: split(trim(output), "\n")
