apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-daniel-rbac
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          fleet: "true"
  template:
    metadata:
      name: team-daniel-rbac-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/dhpup/e2e-platform
        targetRevision: HEAD
        path: apps/team-daniel/rbac
      destination:
        name: '{{name}}'
        namespace: akuity
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
