apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: team-daniel
  namespace: team-daniel
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: prod-demo1
    autoPromotionEnabled: false
  - stageSelector:
      name: prod-demo2
    autoPromotionEnabled: false
