---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: gray
    kargo.akuity.io/argocd-context: '[{"name":"team-daniel-dev","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: features
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: provision-backend
      - task:
          name: promote-guestbook