---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: gray
    kargo.akuity.io/argocd-context: '[{"name":"team-daniel-dev","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: provision-backend
      - task:
          name: promote-guestbook

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-demo1
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: green
    kargo.akuity.io/argocd-context: '[{"name":"team-daniel-prod-demo1","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: provision-backend
      - task:
          name: promote-guestbook








---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-demo2
  namespace: team-daniel
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    kargo.akuity.io/color: green
    kargo.akuity.io/argocd-context: '[{"name":"team-daniel-prod-demo2","namespace":"argocd"}]'
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: team-daniel
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      steps:
      - task:
          name: provision-backend
      - task:
          name: promote-guestbook
